# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34a05e764c53307da157254e35e330097bafdc9f4c96434326ac071d1c3df4737a64e151a994188f5b05409fe2e07e03918a9326a564e3267a2d2af2b29e2f4d

test:
  secret_key_base: db7d94e129cb7d47ef40c0cbe5d41b8e14ddb77a023f27cb43a96edbd036c195656d414845210e312b92b5071ad9e504154805ec0479cebc7dde4a8734e6e696

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
